### ISSUE TITLE
DDD altering undefined armors pieces.

### ISSUE THREAD

**Issue by evilchin** [yeelp/Distinct-Damage-Descriptions#102]
When you use an undefined piece of armor in DDD, it provides zero protection. Is there any possibility of having this instead work like shields do, weapons, or possibly having them fall back to vanilla behavior and working for anything basically? I think the easiest solution is to have undefined armors use vanilla behavior personally, but I am mostly unaware of how easy/difficult that would be to implement on your end. Or perhaps you could just have a "default" armor distribution that applies to any undefined armor pieces (and hopefully it can be edited in the config).

I bring up this issue as I personally only want to use the mod for mob damage types/resistances and weapon damage distributions. I get this is super inconvenient to ask this, but I figured it would be worth bringing some attention to for the sake of transparency. Let me know if you need any more info. Sorry for any possible troubles!

**Comment by yeelp** [comment]
> Or perhaps you could just have a "default" armor distribution that applies to any undefined armor pieces

So fun fact, DDD *does* have default damage, armor and shield distributions, however they aren't configurable and are used internally when an item doesn't have a distribution set for it.

I could add an option to toggle how these default distributions behave though (for armor: either no effectiveness or 100% effectiveness), that shouldn't be an issue. It likely won't have undefined armor go back to their vanilla behaviour, just due to how DDD handles damage from multiple types at once, but it would likely be somewhat close.

**Comment by Xarmat-GitHub** [comment]
This would be a good solution. 
Modpack maker's get the control over the default behavior and can tweak it as needed. 👍

**Comment by evilchin** [comment]
Yea I just want to have armor do something when it isn't configured basically. What you suggested is exactly what I'm looking for essentially.

**Comment by evilchin** [comment]
Forgot to close this a while back after your latest update. Armor settings seem to work well enough, so I'm just going to close this for now. Feel free to re-open this if I missed something related to this issue.
