### ISSUE TITLE
[Suggestion] Hidden Damage Types

### ISSUE THREAD

**Issue by Xarmat-GitHub** [yeelp/Distinct-Damage-Descriptions#109]
### Suggestion:
Give Pack-Makers the option to hide costume ddd types from all sources (weapons, armor, shields, mobs, etc.) by adding some sort of tag to there own custom damage types "hide_type: true".

This gives Modpack Makers options to add ddd types that are not communicated to the player and can be used for immersion stuff like:
- "This monster can only be killed by dragon fire!" (ddd_hidenfire) -> weapon & mob
- "All Void Weapons (Thaumcraft) do extra damage to crimson cult." (ddd_hiddenvoid) -> weapon & mob
- "This Armor saves the wearer from damage from all mobs in the deep dark dimension." (ddd_hiddenshadow) -> armor & mob

I am not sure how often this will be used, but it may will reduce tool-tips size on items and monsters a lot if someone want to use it this way.

**Comment by yeelp** [comment]
Not only do I like this, but this aligns well with an interesting situation I encountered with some of DDD's built in "internal types". I didn't really want them showing on tooltips for armor when "assume 100% effectiveness for unspecified types" is set (a config option that doesn't have an open issue in the repo; basically specify something like [(s, 0.6), (b, 0.8)] for armor and it gives those effectiveness ratings but all other types have 100% effectiveness instead of the normal 0%, if that made any sense).

Anyway yes, this actually makes a lot of sense.

**Comment by yeelp** [comment]
Added in 1.7
