### ISSUE TITLE
The damagedistribution of tconstruct's tool didn't change when I change the material of head part

### ISSUE THREAD

**Issue by xjyjack** [yeelp/Distinct-Damage-Descriptions#113]
> From all my testing and tweaks I have been unable to recreate this. Check on the latest release (1.7). Please reopen if you get the problem in the latest release
Sorry for open a new issue.But as I'm not the issue closer, I can't open it. 
I tried 1.7 version, and if the modlist still only contain ddd,mantle and tconstruct, the damage distribution work properly.But once I put a tinker's addon( I tried 
 plustic and tinkers'reforged) and I enter an existing world, 
after a tool's head part was changed into firewood, it's damagedistribution is fixed to fire100% and won't change no matter what its head part is changed into any material.
<img width="213" alt="屏幕截图 2024-11-11 200434" src="https://github.com/user-attachments/assets/d84236dc-be5e-478b-a295-aafd61d3f076">
![2024-11-11_20 10 08](https://github.com/user-attachments/assets/be5f4e51-7edd-4207-a5c0-6146c6bf0c2e)
![2024-11-11_20 10 20](https://github.com/user-attachments/assets/9e8967b1-f4f3-4da2-b8eb-845bd963d8ea)

_Originally posted by @xjyjack in https://github.com/yeelp/Distinct-Damage-Descriptions/issues/110#issuecomment-2468032798_

**Comment by yeelp** [comment]
What heppens if you don't enter an existing world with these mods? Could be that the existing world has something that's sort of broken.

**Comment by xjyjack** [comment]
> What heppens if you don't enter an existing world with these mods? Could be that the existing world has something that's sort of broken.

well, if I create a new world with these mods, the distribution still works.But since the second i enter a world, it loses control.

**Comment by yeelp** [comment]
I've looked into this with plustic installed and haven't really been able to recreate it to the same extent. Here's what I've done:

- Load an existing world I created before plustic was installed where I created a Cobalt broadsword.
- Go back to tool forge and swap for Firewood blade.

Nothing unusual happens. It shows the right distribution. Then I did this:

- Swap back to Cobalt blade. Go to the tool forge and put a Firewood blade into it. Close the GUI.
- Go back to the tool forge and shift click the sword into the slot. The Firewood blade is already there so it immediately shows the output.

This sword says it does Fire damage with a cobalt blade. But it's only temporary. Opening my inventory again and checking the blade shows the correct distribution.

Even still, I managed to recreate the problem using a combination of Ardite, Cobalt and Firewood blades. Shift clicking into the forge with a blade already there, swapping back and forth until the distribution said it didn't match. The distribution said 88% slashing and 12% necrotic with a cobalt blade. That's what it should be with ardite. I go and hit a mob and check debug output. It does the correct damage (just slashing with a cobalt blade). 

You can verify this yourself. Go to the mod's config. The go to development tools. Set `Enabled` to `true` and set `Show Damage Classification` to `ENABLED_AND_IN_CHAT`. With your sword, go hit any mob. Should show the correct damage types and the correct calculations should be performed.

Try a couple other things too. Try reloading the world when you have that problem, or try making a new tool and see if it has the same problems. I don't know what to suggest, I quite literally don't get the same problems. The best I can say right now is that this is a strange inconsistent anomaly that happens when updating DDD to 1.7 from an older version.

**Comment by xjyjack** [comment]
> I've looked into this with plustic installed and haven't really been able to recreate it to the same extent. Here's what I've done:
> 
> * Load an existing world I created before plustic was installed where I created a Cobalt broadsword.
> * Go back to tool forge and swap for Firewood blade.
> 
> Nothing unusual happens. It shows the right distribution. Then I did this:
> 
> * Swap back to Cobalt blade. Go to the tool forge and put a Firewood blade into it. Close the GUI.
> * Go back to the tool forge and shift click the sword into the slot. The Firewood blade is already there so it immediately shows the output.
> 
> This sword says it does Fire damage with a cobalt blade. But it's only temporary. Opening my inventory again and checking the blade shows the correct distribution.
> 
> Even still, I managed to recreate the problem using a combination of Ardite, Cobalt and Firewood blades. Shift clicking into the forge with a blade already there, swapping back and forth until the distribution said it didn't match. The distribution said 88% slashing and 12% necrotic with a cobalt blade. That's what it should be with ardite. I go and hit a mob and check debug output. It does the correct damage (just slashing with a cobalt blade).
> 
> You can verify this yourself. Go to the mod's config. The go to development tools. Set `Enabled` to `true` and set `Show Damage Classification` to `ENABLED_AND_IN_CHAT`. With your sword, go hit any mob. Should show the correct damage types and the correct calculations should be performed.
> 
> Try a couple other things too. Try reloading the world when you have that problem, or try making a new tool and see if it has the same problems. I don't know what to suggest, I quite literally don't get the same problems. The best I can say right now is that this is a strange inconsistent anomaly that happens when updating DDD to 1.7 from an older version.

I made a video so you could clearly see what happens,in this video, you could see my modlist and the forgecap of broadsword.

https://github.com/user-attachments/assets/aaba033e-a4fa-4ed3-a560-8e81663785d8
