### ISSUE TITLE
[Suggestion] Config Structure

### ISSUE THREAD

**Issue by Xarmat-GitHub** [yeelp/Distinct-Damage-Descriptions#29]
### Make the Mod accessible - Config Structure
**Mod Complexity**
Have a tool to control many thinks is great, when the user base wants to use it.
Else it is terrifying and all users run away when thinks get to complex.
To reduce this effect, it would be good to split things into "Tiers".
**Goal:** Player that just want use one/some feature, don`t get in touch with the other.
Possibility's to handle this:
- **Create More Configs**
+ Basic Config
++ Contains Basic (Turn on/off basic mechanics of the mod. Armor, Shield, Weapon, "Magic" damage calculation behaviour)
++ (This is relevant, when the Mod adds automatic values to all sorts of Items form all Modpacks. So this is "future" talking) _see *A_
+ Advanced Config (Enable the extra Mechanics here and dive in an epic balancing fight)
++ Enable Custom Damage Types and create own System ON TOP the Basic once
++ After restarting the game once, a new folder will be created with the "custom damage" files in it - with examples from easy to complex

_________________________________________________________________
_*A_: In my mind, this mod adds some base values for all Items, entitys in all Mods. So when the player just drop it into the folder, all works fine and he don't have to mess with configuration. This will need work from the community to set some kind of lists that Yeelp can add to the mod.

**Comment by yeelp** [comment]
This is a fair point. Accessibility is important. A 'drag and drop' mod would be great, which is why #10 exists. Generating random (or algorithmically determined) config values on the fly for modded mobs is a great start. But having some 'out of the box' values for some popular mods definitely isn't a bad idea either.

I'm currently working on a Discord server for people to gather and discuss my mods (Scaling Feast, this mod), so that would be a good place for the community to collaborate and come up with some default values for modded mobs. Then someone can open a PR with the additions to the config and I'll happily merge it.

Having a complex config directory structure can help with organizing basic config features form complex config features. but I'd need to write my own config loader at that point (Forge will only load from <modid>.cfg in the config directory). I'm not completely opposed to the idea, but I'd like to focus on other features first. It'll help give me an idea as to how I'd like to organize the config structure, if anything.

**Comment by Xarmat-GitHub** [comment]
I have a question: You tagged this ticket with "help wanted".
Is there a way to help right now, or do you have to configure stuff first?

**Comment by yeelp** [comment]
(Took me a moment to remember why I tagged it like this)

I have this tagged as help wanted as I agree with your suggestion of having the community come up with preset config values for some popular mods. Anyone can open a PR with those config values (or tweaks to original config values if it's warranted) and I'll merge it if I like the changes/suggestions.

**Comment by yeelp** [comment]
This issue is being closed as the config structure is "good enough" right now.
