### ISSUE TITLE
[BUG] Testing 1.4 Tinkers / Conarm Pre-release 2

### ISSUE THREAD

**Issue by Xarmat-GitHub** [yeelp/Distinct-Damage-Descriptions#77]
### [I am not finished with testing, I will put all outcome in this ticket]

Test List:
- Conarm Damage Reduction
- Conarm different materials
- Tinkers Items testing
- Tinker Calculation testing
- Shield Blocking with Vanilla + Spartan Shields
- Making custom Tinkers Weapons with NBT changes and test the result
- Making custom Conarm Armor with NBT ingame NBT editing and test the result
- B:"Generate Configs"=true -> check what happens
- Create custom damage types
- Player Resistances
- HUD testing, information display
- Testing Dev Tools

**Comment by Xarmat-GitHub** [comment]
**This was fast, first bug:**
[crash-2021-12-01_19.10.53-client.txt](https://github.com/yeelp/Distinct-Damage-Descriptions/files/7636238/crash-2021-12-01_19.10.53-client.txt)

So having JEI installed and hovering over an tinkers item will crash the game.

My Config:
https://pastebin.com/QE64Dbui

**Comment by Xarmat-GitHub** [comment]
Debugmode two triggers / one to much:

- B:"Debug Mode"=true
and
- "development tools" -> B:Enabled=true

So it exist two times. Reduce it to one element would be good.

**Comment by Xarmat-GitHub** [comment]
Player don't receive damage.

I created a new world and spawn an Polar Bear.
Changing Gamemode to survival and poke the bear.

He does nothing to me, no damage and no knockback and no damage sound.

This shows in the console:

[01/12/2021 19:37:40 PM] [Server thread/INFO] [yeelp.distinctdamagedescriptions.util.development.DeveloperModeKernel]: [DISTINCT DAMAGE DESCRIPTIONS (DEVELOPER)]: DETERMINE DAMAGE: Damage Classification
[01/12/2021 19:37:40 PM] Slashing: 1.50
[01/12/2021 19:37:40 PM] Bludgeoning: 4.50
[01/12/2021 19:37:40 PM] 
[01/12/2021 19:37:40 PM] [Server thread/INFO] [yeelp.distinctdamagedescriptions.util.development.DeveloperModeKernel]: [DISTINCT DAMAGE DESCRIPTIONS (DEVELOPER)]: ATTACK: Direct Attacker: Polar Bear (minecraft:polar_bear) | Attacker: Polar Bear (minecraft:polar_bear) | Defender: **MINECRAFTUSERNAME** | Source: mob | Current Damage: 6.00

**Comment by Xarmat-GitHub** [comment]
Console don't show weaknesses.

I can not find weakness calculation / information in the console.
Resistance and Immunitys are show.

So **S:"Show Defense Classification"=ENABLED** only work on Resistance and Immunitys

**Comment by Xarmat-GitHub** [comment]
No Informations on how effective the armor is:
![grafik](https://user-images.githubusercontent.com/69967920/144295443-b72ada22-b4b9-446e-981f-64616327e7f5.png)
Note: I have craft this armor in the world regularly.

**Comment by yeelp** [comment]
Thanks for the feedback! The first crash was something I didn't find because I had "Never Hide Info" set to true. I'm a little surprised that it causes a crash when set to false, but it still seems to be an easy fix regardless.

The debug mode and development mode are too different things. The development mode is for showing useful info for pack making (and also debugging). It sends info to the chat in specific instances and will remain consistent across updates, unless a new feature is added. Debug mode is mainly just for me, so I can print out debug information without having to remember to remove the debug lines before release. What info gets printed in the console with debug mode won't be consistent at all, nor would it be presented nicely, as it's mainly for me. Debug mode doesn't have to be on for the development mode features to work.

I also double checked, and the issue you encountered with the polar bear is because of peaceful mode.

Weakness should be shown in the console still, just as a negative resistance value (as that's what a weakness value is internally). Of course, I can add some special handling to display it as a weakness value.

Lastly, for the conarm issue, this isn't a DDD problem per se, but a Conarm one. Conarm calculates armor values and the like on the fly (Conarm armor implements the Forge ISpecialArmor to do this, and this is likely why Tinker tools don't have this problem, but I haven't tested it). What I can try to do is to get the attribute modifier for the armor piece instead of the direct armor value and see if that changes things.
